In [8]:
import pandas as pd
weather_df = pd.read_csv("/Users/lindseyvalput/Desktop/Web-Design/Notebooks/weather.csv")

In [9]:
weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,rikitea,-23.1203,-134.9692,79.12,74,0,17.52,PF,1649640668
1,nizhneyansk,0.0000,0.0000,0.00,0,0,0.00,0,0
2,karratha,-20.7377,116.8463,89.04,27,0,8.70,AU,1649640668
3,baglan,36.1307,68.7083,76.50,33,100,1.10,AF,1649640669
4,tuktoyaktuk,69.4541,-133.0374,3.20,66,20,13.80,CA,1649640669
...,...,...,...,...,...,...,...,...,...
605,metro,-5.1131,105.3067,83.95,67,80,5.82,ID,1649640888
606,sokolskoye,57.1412,43.1589,38.61,99,100,2.57,RU,1649640889
607,asadabad,34.7824,48.1185,40.95,40,39,3.00,IR,1649640889
608,maromitsa,59.8683,48.0123,36.61,99,100,7.00,RU,1649640889
609,betare oya,5.6000,14.0833,70.74,85,100,2.30,CM,1649640890

In [11]:
weather_data = pd.DataFrame.to_html

In [17]:
html = weather_df.to_html()
  
# write html to file
text_file = open("index.html", "w")
text_file.write(html)
text_file.close()